version: '3.8'

services: 
    db:
        image: postgres
        ports:
            - 54320:5432
        volumes:
            - .postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ranjit
            - POSTGRES_PASSWORD=ranjit
            - POSTGRES_DB=ranjit
    

volumes:
    postgres_data:
