"""empty message

Revision ID: 03364a47b15f
Revises: d70cef8029a3
Create Date: 2021-03-12 09:21:02.723704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03364a47b15f'
down_revision = 'd70cef8029a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.String(length=50), nullable=True, unique_key=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###
